### ISSUE TITLE
Alternate not applying -20% combo bonus on first activation?

### ISSUE THREAD

**Issue by hadisiswanto62** [deresute-tools/deresute-tools#5]
So, I was messing around with the source code to see how it works and found something weird. Not really big bug though, since it is not common to use alt without other combo bonus with matching timer.

Steps to reproduce:
1. Add ```self.notes_data.to_csv("test.csv")``` on line 87 of src/simulator.py
2. Run the following lines
```
cards = [Card.from_query(i) for i in ["mio2", "karen4", "nagi2", "aiko4", "shin3", "sachiko2"]]
unit = Unit.from_list(cards)
live = Live()
live.set_music(music_name="M@GIC", difficulty=Difficulty.MASTER)
live.set_unit(unit)
sim = Simulator(live)
sim.simulate(perfect_play=True, support=113290)
exit()
```
3. See exported "test.csv"
4. On note 20-24, skill_2 (nagi2, alternate) activates without any other active skill that overrides the alternate -20% combo bonus, but bonuses_1 is still 0.
On note 142, the same scenario happens but bonuses_1 is correctly -20

Is this the correct behavior? I don't have alternates in game so I can't check it.

**Comment by dlresearchsociety** [comment]
There's no _first activation_ even in this case. Alt just does not activate at all in this example (thus no -20% combo bonus) since there is no skill with a score bonus that activates before/at the same time with Alt.

**Comment by hadisiswanto62** [comment]
thanks! i was not aware of this interaction
